### ISSUE TITLE
Budowa interfejsu użytkownika

### ISSUE THREAD

**Issue by pkonieczny04** [pkonieczny04/NPG_Kalkulator_Projekt#22]
1. Inicjalizacja GUI: Zbudowanie głównego okna aplikacji oraz pola tekstowego do wyświetlania i wprowadzania danych.
2. Definicja metody __init__: Utworzenie głównego okna (root), tytułu okna, pola wprowadzania (Entry) dla wyrażeń matematycznych.

**Comment by TMLMarJ** [comment]
Wykonano nowy branch i plik zawierający metodę init i inicjalizację GUI
